name: deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.17

      - name: Install Packages
        run: yarn install --frozen-lockfile

      - name: Run prettier
        run: yarn run prettier-check

      - name: Run lint
        run: yarn run lint

      - name: Run flow
        run: |
          yarn run flow-check-annotation
          yarn run flow

      - name: Run tests
        run: yarn run test

      - name: Build App
        run: yarn run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
