name: pull-request

on:
  pull_request:
    branches:
      - master

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.18.4

      - name: Install Packages
        run: yarn install --frozen-lockfile

      - name: Run prettier
        run: yarn run prettier-check

      - name: Run lint
        run: yarn run lint

      - name: Run flow
        run: |
          yarn run flow-check-annotation
          yarn run flow

      - name: Run tests
        run: yarn run test
